### ISSUE TITLE
Accessibility - Dataverse - Unique ID Attribute Value

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#105]
### Add a New Data Project: https://data.qdr.syr.edu/dataset.xhtml?ownerId=1
- [ ] Files Box
![image](https://user-images.githubusercontent.com/89411909/138353624-35e43755-3d29-40c8-a46d-0b260480ceda.png)

**Comment by qqmyers** [comment]
Schema used an id instead of a class and then put it in several places. I changed it to a class. file-row-panel-backdrop was just used for css (now looking for a class rather than an id), so I don't expect any issues.
