### ISSUE TITLE
QA on 5.8: Bug when trying to open an old project

### ISSUE THREAD

**Issue by nniiicc** [QualitativeDataRepository/dataverse#108]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
On stage witht he DV 5.8 prototype 

* Which page(s) does it occurs on?
 https://data.stage-aws-new.qdr.org/dataset.xhtml?persistentId=doi:10.33564/FK2IDODKG

* What happens?
This is a report from a GA at SYR - there is a major bug when trying to open an old project

* To whom does it occur (all users, curators, superusers)?
Curators and users 

* What did you expect to happen?

**Which version of Dataverse are you using?**

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by qqmyers** [comment]
This was an old security test, demonstrating that one could inject a script into a dataset. The flaw itself had been fixed. However, bad inputs can be cached in the exported metadata files. I've now reexported the metadata files and the problem is gone.
