### ISSUE TITLE
QA on 5.8: SSO redirects 

### ISSUE THREAD

**Issue by nniiicc** [QualitativeDataRepository/dataverse#109]
**What steps does it take to reproduce the issue?**
This is a bug that can't be systematically produced - but may be worth investigating

* When does this issue occur?

"The SSO seems a bit weird, I feel like I got redirected 3+ times sometimes. Couldn't reproduce any consistent problems though" 

* Which page(s) does it occurs on?

* What happens?

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?

**Which version of Dataverse are you using?**

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by nniiicc** [comment]
This might be a product of STAGE rather than anything specific to 5.8

**Comment by qqmyers** [comment]
Is this our SSO mechanism (perhaps slower on stage than prod)? If you haven't logged in, when you go to a Dataverse page, you'll be redirected to the Shib app which then redirects you back to Dataverse, potentially logged in if you had already logged in to Drupal. 
One way to test is to just ctrl-refresh the page. With the SSO mechanism, once the passive login check has run once, it won't happen again, so the refresh should not go through the redirect sequence.

**Comment by nniiicc** [comment]
That was my suspicion - Thanks Jim
