### ISSUE TITLE
Tags out of order in Version diff

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#44]
Looking at https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F65BVECY&version=DRAFT 
The only change made between currently published and DRAFT version is the Note metadata.
However, the Version tab --> Details also shows a file metadata difference, with the order of two tags reversed.
![image](https://user-images.githubusercontent.com/128986/85434112-89617500-b553-11ea-90fb-6a81bf8de1fc.png)

What's particularly strange is that I'm fairly certain the exact same draft version displayed a different set of out-of-order file tags yesterday

**Comment by qqmyers** [comment]
Looks like the comparison was done against the results returned from the db (which apparently is not ordered) rather than the sorted list of categories. https://github.com/QualitativeDataRepository/dataverse/commit/7f930b3c17d51f0fc9adaa8a30742592b7487564 should fix it.
