### ISSUE TITLE
Log in link for Access Request on file landing page is incorrect

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#45]
E.g. as anonymous go to https://data.qdr.syr.edu/file.xhtml?persistentId=doi:10.5064/F65BVECY/ZBB1SJ&version=2.0
Click on "Request Access" then click on Log in
The link goes to https://data.qdr.syr.edu/file.xhtml?redirectPage=%2Ffile.xhtml%3FpersistentId%3Ddoi%3A10.5064%2FF65BVECY%2FZBB1SJ%26version%3D2.0 (which makes no sense and leads to a 404

The access request for the file from the file list on the project page links to the correct https://qdr.syr.edu/user/login?current_page=https://data.qdr.syr.edu%2Fdataset.xhtml%3FpersistentId%3Ddoi%3A10.5064%2FF65BVECY%26version%3D2.0

**Comment by qqmyers** [comment]
Fixed with https://github.com/QualitativeDataRepository/dataverse/commit/06b682d823841e70be5fe4cb94c8486cb6c4ef23
