### ISSUE TITLE
Customize Publication email

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#47]
Would it be possible to customize the "Your data project has been published" email as follows?

> Hello, 
>You data project "[TITLE]" was published in QDR. You can view it at [LINK].
>
>Please always use the recommended citation to refer to your project:
>[CITATION]
>
>When linking to the data, we recommend to always use the DOI, [resolved DOI].
>
>Thank you for depositing your data with QDR. Please be in touch with any questions or concerns qdr@syr.edu.
>
>Thank you,
The Qualitative Data Repository

**Comment by qqmyers** [comment]
Sure. The text is just a string but the code doesn't yet allow you to access the Citation or DOI in the message, so it will require some code changes - probably useful to the community as well.

**Comment by qqmyers** [comment]
Updated on dev to read:

Hello, 
Your data project "Test" was published in QDR. You can view it at https://dv.dev-aws.qdr.org/dataset.xhtml?persistentId=doi:10.33564/FK2OZYVTW.

Please always use the recommended citation to refer to your project:
	Myers, Jim. 2020. "Test". Qualitative Data Repository. https://doi.org/10.33564/FK2OZYVTW. QDR Main Collection. V1

When linking to the data, we recommend to always use the DOI, https://doi.org/10.33564/FK2OZYVTW.

Thank you for depositing your data with QDR. 

Please be in touch with any questions or concerns qdr@qdr.mail.syr.edu.

Thank you,
The Qualitative Data Repository

Getting rid of the spaces between the Thank you and Please be in touch lines requires shifting the two \n\n chars from the begging of the closing statement ('\n\nPlease be in touch...') to the end of the body in other types messages - can do that but would have to find/edit other email message types so I thought I'd check to see whether it was worth the effort.

@adam3smith -let me know about that and any other changes you'd like and then I can push it to stage, etc.

**Comment by adam3smith** [comment]
Thanks -- looking good. A couple of tweaks seeing the whole message:

-  It looks like there's a tab character at the beginning of the sample citation that looks weird:
![image](https://user-images.githubusercontent.com/128986/86935290-a7f66d00-c10a-11ea-8a6b-04ff9877fefc.png)

- Can we do away with the "Hello," It looks weird. Instead, let's try "Congratulations! Your data project..."
- Could we just add the "Thank you for depositing your data" at the end of the first paragraph? So full message:

> Congratulations! Your data project "One eyed one horned flying purple people eater" was published in QDR. You can view it at https://dv.dev-aws.qdr.org/dataset.xhtml?persistentId=doi:10.33564/FK2LSJCQI. Thank you for depositing your data with QDR.
> 
> Please always use the recommended citation to refer to your project:
> Test, Lara. 2019. "One eyed one horned flying purple people eater". Qualitative Data Repository. https://doi.org/10.33564/FK2LSJCQI. QDR Main Collection. V3. UNF:6:uqWppXTqqwswPkrzei8EdA== [fileUNF]
> 
> When linking to the data, we recommend to always use the DOI, https://doi.org/10.33564/FK2LSJCQI.
> 
> Please be in touch with any questions or concerns qdr@qdr.mail.syr.edu.
> 
> Thank you,
> The Qualitative Data Repository

**Comment by qqmyers** [comment]
@adam3smith - the "Hello,\n" is a standard line across emails. I can remove it from all types of emails, or change the published dataset email to not use it. Or leave as is. Any preference?

**Comment by qqmyers** [comment]
FYI: other changes are on dev now.

**Comment by adam3smith** [comment]
Let's remove the "Hello,\n" across the board. People realize these are computer generated.

**Comment by qqmyers** [comment]
OK - There are some emails that look like they get Hello separately (One with Hello <firstname> <lastname>), but I've dropped the common Hello, greeting so any emails that use that will drop it. 

I've deployed the changes to dev and stage.

**Comment by adam3smith** [comment]
Has been deployed to prod
