### ISSUE TITLE
Select Thumbnail Pop-up is transparent

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#48]
Tested on Stage & Prod
To reproduce:
Data Project --> Edit --> Thumbnail and Widget

In the Thumbnail tab select "Select Thumbnail". This is purely cosmetic, everything functions as expected.

![image](https://user-images.githubusercontent.com/128986/86689334-e38f1b00-bfd4-11ea-9750-ef02f46d4c11.png)

**Comment by qqmyers** [comment]
Fixed on dev and stage (may need to clear cache)  - made a change to make dialogs opaque - this one and any others with the same classes. I haven't checked to see what that might have affected, but it seems like a reasonable default. (Should leave the background:none style on body .ui-widget .ui-widget-content which is what I think was intended.)

**Comment by adam3smith** [comment]
Has been deployed to prod
