### ISSUE TITLE
Sign-up for GeoLite2 DB updates and implement the auto-update mechanism for MDC

### ISSUE THREAD

**Issue by qqmyers** [QualitativeDataRepository/dataverse#51]
This database allows Dataverse to look at the user's URL and infer a geolocation that is used in MDC to bin visits/downloads by country and state. The geo-database is free and there fairly recent copies with no license terms. The latest versions now require you to sign an agreement to keep up-to-date with new releases. (Geomind, the distributor is trying to comply with GPDR and similar privacy laws by coming up with a way to assure takedown requests are handled even for free copies they distribute.) 

Links:
[Maxmind's Reasons for making the change](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) 
[Registration page](https://www.maxmind.com/en/geolite2/signup)

Registration should allow creation of a free license key for the GeoLite2 database

With the key, we can configure automatic weekly checks and automated downloads of the database using the GeoIP Update program.

**Comment by qqmyers** [comment]
Install process, using our config info, is:

```
wget https://github.com/maxmind/geoipupdate/releases/download/v4.3.0/geoipupdate_4.3.0_linux_amd64.tar.gz
tar xvf geoip*
mkdir /opt/geoipupdate
mv geoipupdate_4.3.0_linux_amd64/* /opt/geoipupdate
cd /opt/geoi*
cp GeoIP.conf /usr/local/etc
vi /usr/local/etc/GeoIP.conf
```
add our account/license key/editionIDs, set DatabaseDirectory /opt/counter-processor-0.0.1/maxmind_geoip
Test/update with 
`./geoipupdate
`
Then
`crontab -e`
add
`6 23 * * 4 /opt/geoipupdate/geoipupdate`

**Comment by qqmyers** [comment]
done on dev, stage, and prod - verified that the country db file has an Oct 14 date now (and the ASN and City dbs (~70MB) have been added)

**Comment by qqmyers** [comment]
Verified that the script has updated the DBs as of Oct. 29th so it looks like this is complete.

**Comment by adam3smith** [comment]
Great, thanks!
