### ISSUE TITLE
Login link from "Request Access" on File landing page fails

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#53]
Go to a file landing page, e.g. https://data.qdr.syr.edu/file.xhtml?persistentId=doi:10.5064/F6MS3QNV/PBR0DQ (reproduced for others, too)
Click on "Request Access"
Click on "Log in"
--> Dataverse shows 404/file not found error with this URL:
https://data.qdr.syr.edu/file.xhtml?redirectPage=%2Ffile.xhtml%3FpersistentId%3Ddoi%3A10.5064%2FF6MS3QNV%2FPBR0DQ

**Comment by qqmyers** [comment]
The required change is in the file.xhtml page and could be deployed to prod with a local edit and server restart (versus a full redeploy). Should be fixed on dev.

**Comment by adam3smith** [comment]
fixed in latest release on prod
