### ISSUE TITLE
dataverses/bySubject metrics endpoint doesn't return JSON

### ISSUE THREAD

**Issue by donsizemore** [QualitativeDataRepository/dataverse#56]
```
$ curl https://data.qdr.syr.edu/api/info/metrics/datasets/bySubject
subject,count
"Social Sciences",80
"Medicine, Health and Life Sciences",20
"Law",5
"Other",3
"Earth and Environmental Sciences",2
"Agricultural Sciences",1
```

vs.

```
$ curl -k https://dataverse5.odum.unc.edu/api/info/metrics/datasets/bySubject
{"status":"OK","data":[{"subject":"Computer and Information Science","count":12},{"subject":"Social Sciences","count":10},{"subject":"Mathematical Sciences","count":3},{"subject":"Agricultural Sciences","count":2},{"subject":"Arts and Humanities","count":2},{"subject":"Other","count":2},{"subject":"Earth and Environmental Sciences","count":1},{"subject":"Medicine, Health and Life Sciences","count":1},{"subject":"Astronomy and Astrophysics","count":1},{"subject":"Engineering","count":1}]}
```

**Comment by qqmyers** [comment]
This is trickier - the new API sends csv unless you request 'application/json' which the old code doesn't do (and probably should). The https://github.com/IQSS/dataverse-metrics/pull/52 includes that if you want to update/cherry pick from there. I think this would be backward compatible since the old API always sends JSON and ignores any request for a specific type.

**Comment by qqmyers** [comment]
Ah - @donsizemore  - I think you're correct - I didn't go back to adjust the python code. I'll take a look.

**Comment by qqmyers** [comment]
I'm going to close these two issues - with an update to the dataverse-metrics code to Accept application/json, the metrics code can/does retrieve json, with the Dataverse code working as intended. If there's interest in flipping the default to json, it will probably be handled in the [#7178](https://github.com/IQSS/dataverse/pull/7178) PR or a new issue at IQSS.
