### ISSUE TITLE
Curation Label display does not update immediately when changed consecutively without reload

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#63]
Expected and default behavior:
1. Use "Change Curation Status" to add or change a curation status
2. The data project page displays a notification bar and the curation bar and changes the pink label on the dataset.

Incorrect behavior:
When performing the above action twice immediately in a row, the status bar does appear and the status does change, but the label on the data project does not.

Tested on Edge and Firefox

**Comment by qqmyers** [comment]
Due to the page having a cached copy of the dataset version with the old status value. Now fixed.

**Comment by adam3smith** [comment]
Fix confirmed
