### ISSUE TITLE
Remove UNF from sample citation

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#64]
There seems to be a lot of reluctance to move on this on the DV end (https://github.com/IQSS/dataverse/issues/7328 ) , but I'd like us to just remove the UNF from all sample citations (including old ones). Since DV will likely want to do something more complex here, let's just do this in the simplest possible way without configuration option etc.

**Comment by qqmyers** [comment]
Done. I've just removed the UNF code form the DataCitation class, so it won't appear in citations (displayed or the download formats) but will still get calculated/shown on the page as before. Deployed to dev and stage.
