### ISSUE TITLE
Accessibility - Discernable Text for Buttons

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#66]
Homepage: https://qdr.syr.edu/
Issue: "Buttons must have discernable text" - Hamburger menu button in top left corner

![image](https://user-images.githubusercontent.com/89411909/131692110-c629e4cd-35f6-47eb-b44f-b8b18c437d94.png)

**Comment by adam3smith** [comment]
label as main menu

**Comment by qqmyers** [comment]
"Main Menu"

**Comment by qqmyers** [comment]
I added aria-labels to the button above ("Main Menu") and the 'X'/Close button that appears when you open the main menu. I used "Close Main Menu" for that. Is there a pattern for action buttons we should use (same label for both, or Open X /Close X, or?)

Note that I tried just using an aria-label on the span for #65, but that leads to a new error so I kept using a title there.
