### ISSUE TITLE
Accessibility - Alt Text for Images

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#68]
Homepage: https://qdr.syr.edu/
Issue: "Images must have alternative text"

Images: The four images of sample project files don't have any alternate text.

**Comment by adam3smith** [comment]
alt="" for the theme image.

use alt text from DV for project thumbnails

**Comment by qqmyers** [comment]
empty for decorative, match DV for others

**Comment by qqmyers** [comment]
As a first step, I added alt="<Dataset Title> logo" to the DV images (and set alt="" for the internal one.
