### ISSUE TITLE
Accessibility - Link Text

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#69]
### Homepage
URL: http://qdr.syr.edu/

- [x] Link: Qualitative Data Repository in the top left corner (next to menu button) needs accessible text. 

### Conferences, Workshops, and Training: https://qdr.syr.edu/guidance/workshops

- [x] Link: Summer Institute in Empirical Implications of Theoretical Models
- [x] Link: FCSH Digital Humanities Summer School
- [x] Link: Berkley Initiative for Transparency in the Social Sciences: Research Transparency and Reproducibility Training (RT2)

### Privacy: https://qdr.syr.edu/policies/privacy
- [x] Link: Harvard Dataverse
- [x] MDN web docs
- [x] CC-BY-SA

**Comment by qqmyers** [comment]
link title - Qualitative Data Repository
aria-label - got to homepage

**Comment by adam3smith** [comment]
Homepage links:
title="Qualitative Data Repository" arila-label="Go to home page"

Rest: Theresa and Sebastian will address

**Comment by qqmyers** [comment]
Fixed the menu links

**Comment by adam3smith** [comment]
Fixed empty links
