### ISSUE TITLE
Accessibility - Links with Same Name

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#70]
### Homepage: https://qdr.syr.edu/

- [x] "Discover More" link under "Managing Data" header and "View Project" under US Cold War Documents have the same accessible name

### Resources: https://qdr.syr.edu/qdr-resources

- [x] Deposit Process link in blue box
- [x] Policies link in blue box
- [x] Discover More links under Formatting Data and Preparing a Data Project...

**Comment by qqmyers** [comment]
aria-label discover more about

**Comment by qqmyers** [comment]
show all items - aria-label ... in <x>

**Comment by adam3smith** [comment]
To be determined: 

- [ ] Duplicate "Policies" (filter and footer)
- [ ] Do we need to label the filter buttons?

**Comment by adam3smith** [comment]
I think the links on the resource page are similar enough to qualify.
