### ISSUE TITLE
Accessibility - Heading Levels

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#71]
### Homepage: https://qdr.syr.edu/

- [x] "Project Summary" heading (h3) under Marine Corps Organizational Culture Research Project 
- [x] "More Info" heading (h4) under The Qualitative Data Repository Logo footer

### Blog: "Qualitative Data Repository Teams with...": https://qdr.syr.edu/qdr-blog/qualitative-data-repository-teams-hypothesis-develop-annotation-transparent-inquiry-ati

-[ ] 
![image](https://user-images.githubusercontent.com/89411909/133820009-b586a7c7-4b7b-4c92-b45e-c6df9fddbeb3.png)

**Comment by qqmyers** [comment]
For footer - don't use H4
For Project summary - make title H2

**Comment by qqmyers** [comment]
Added title as H2 for teaser paragraphs, changed footer blocks to use <p> instead of <h4> for first element and then added styles for p:first-child for those blocks to apply the same styling.
