### ISSUE TITLE
Accessibility - Landmarks for Page Content

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#72]
### Homepage: https://qdr.syr.edu/

- [ ] Hamburger Button and "Qualitative Data Repository" logo in the top left corner of the page
- [ ] LogIn Button on the top right
- [ ] Register Button on the top right

**Comment by qqmyers** [comment]
whole header gets HTML5 landmark and role: navigation
main
<nav role="navigation">
<main role="main">
<footer role="contentinfo">
