### ISSUE TITLE
Accessibility - Drupal - Color Contrast

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#77]
**Texts**
#777777 --> #424242
##4f4f4f --> #666666
h2 opacity (e.g. for "Annotation for Transparent Inquiry") 0.5 --> 0.8

** Backgrounds**
#eaeaeb --> #E8E8ED
#F5F5F7 --> #F6F6F8

**Comment by qqmyers** [comment]
I don't see any #F5F5F7 in Drupal. There is f7f7f9.

**Comment by adam3smith** [comment]
I'm seeing #F5F5F7 as the background of the ATI section
![image](https://user-images.githubusercontent.com/128986/133133142-50275378-28a8-4483-894f-936edf6808ed.png)

Looks hardcoded/inline?

**Comment by 4tikhonov** [comment]
Hi @adam3smith and @qqmyers, it looks like a very interesting development for DANS as well. Do you have a spec for this Drupal plugin somewhere?

**Comment by adam3smith** [comment]
@4tikhonov -- sorry for the confusion, this is actually for our custom Drupal theme. We're not using a DV add-on for Drupal or vice versa. The only reason the issue is here is that I wanted all accessibility issues for our site in one repo rather than in three different places

**Comment by qqmyers** [comment]
This color is defined by the background-color of the specific paragraph in the page, in this case for https://stage-aws-new.qdr.org/content/qualitative-data-repository (on the internal stage server.) So this is something that is in the drupal database, probably easier to just update via the UI when we deploy that to worry about sql. Changed on dev/stage.

**Comment by qqmyers** [comment]
Changed on prod as well
