### ISSUE TITLE
Accessibility: Search box selector in header: Select element must have an accessible name

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dataverse#82]
![image](https://user-images.githubusercontent.com/128986/133493570-abd21fd9-c315-4603-821b-e11bf626f8c8.png)

Details here: https://dequeuniversity.com/rules/axe/4.3/select-name?application=AxeFirefox
If we can do this with label that's preferred, otherwise aria-label will also work

**Comment by qqmyers** [comment]
I ended up using aria-label - since the only text around is the placeholder in the search input, I didn't see a good way to wrap it in a label.
