### ISSUE TITLE
Accessibility - Dataverse - Form Element Labels

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#88]
### Homepage: https://data.qdr.syr.edu/
- [x] Each of the three checkboxes on the left (Collections, Data Projects, Files) 
![image](https://user-images.githubusercontent.com/89411909/134688515-6abfc9b8-e644-4613-9b21-59d5975d5e32.png)

### Advanced Search Page: https://data.qdr.syr.edu/dataverse/main/search
- [x] Every box of the form that you can type in 

### Add a New Data Project Page: https://data.qdr.syr.edu/dataset.xhtml?ownerId=1
- [ ] Identifier Scheme Box
- [ ] Identifier Type Box
- [ ] Notes Box
- [ ] Depositor Name
- [ ] URL Box
- [ ] Group Box

### Homepage: https://data.qdr.syr.edu/
- [x] Dataverse Search Box
- [x] When "Contact" Menu is open: 
![image](https://user-images.githubusercontent.com/89411909/134702639-931fc4e3-182f-4298-af01-a4ee4d4fb505.png)

**Comment by qqmyers** [comment]
Should all be addressed (on dev so far).
