### ISSUE TITLE
Accessibility - Dataverse - Link Text

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#89]
### Homepage: https://data.qdr.syr.edu/
- [x] Magnifying glass on the dataverse search bar
- [x] Three checkboxes on the left side of the page (Collections, Data Projects, Files)
- [x] Every thumbnail that uses the piece of paper graphic: 
![image](https://user-images.githubusercontent.com/89411909/134689950-60f3012a-4a57-4e10-a41e-c4299f73ab84.png)
- [x] All 4 "skip" buttons at the bottom of the page: 
![image](https://user-images.githubusercontent.com/89411909/134690340-39f2a8ab-1f3f-49e4-add0-5f0e4bcb4831.png)
- [x] With the "Share" menu open: the facebook, twitter and linkedin buttons: 
![image](https://user-images.githubusercontent.com/89411909/134703285-b4bd4c62-dbc2-400d-86cc-546e77a42e9a.png)

### (Sample Page) - Data for: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent: https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F6YYA3O3
- [x] The magnifying glass in the "Search this data project" bar

**Comment by qqmyers** [comment]
Should all be fixed on dev. I used a mix of titles (which show when you hover over) and aria-labels, which only matter to screen readers. So, for example, the pager buttons now have titles that say First, Previous, Next, Last if you hover over them. If we don't want that, these could be aria-labels.

**Comment by adam3smith** [comment]
I like using titles on the unlabelled buttons, yes
