### ISSUE TITLE
Accessibility - Dataverse - Landmarks

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#92]
### Homepage: https://data.qdr.syr.edu/
- [ ] QDR Main Collection (on all pages it appears)
![image](https://user-images.githubusercontent.com/89411909/134696619-5ec7d187-e8c1-499d-94ef-7fbc39b1bf0c.png)
- [ ] Metrics/Contact/Share
![image](https://user-images.githubusercontent.com/89411909/134696723-77944436-695f-46d0-9376-359d3558be0f.png)
- [ ] Search Bar
![image](https://user-images.githubusercontent.com/89411909/134696765-df98445c-c8d6-4c76-b244-a4ee0654cc87.png)
- [ ] Advanced Search 
![image](https://user-images.githubusercontent.com/89411909/134696913-5087cbf7-f4fb-4af6-bdef-e503ae79e38a.png)
- [ ] New Project 
![image](https://user-images.githubusercontent.com/89411909/134697072-aa6c6302-b3fb-4cf2-a8fc-6570105831fa.png)
- [ ] Filters 
![image](https://user-images.githubusercontent.com/89411909/134697638-9893b755-9217-4c57-9cf2-ab99e46c93ad.png)
- [ ] Each of the three checkboxes (Collections, Data Projects, Files): 
![image](https://user-images.githubusercontent.com/89411909/134697815-ed9e31b9-6273-4101-be0d-4f288edecb8c.png)
- [ ] Left Menu (starting with Collection Category) 
![image](https://user-images.githubusercontent.com/89411909/134697943-ef5648c8-6b53-4a2a-8f8e-4c435ef97dcc.png)
- [ ] Results Numbers 
![image](https://user-images.githubusercontent.com/89411909/134698003-9c9e44a7-f3e2-4ed9-a782-3a19f6fcec1e.png)
- [ ] Sort 
![image](https://user-images.githubusercontent.com/89411909/134698045-0cb41117-52c3-4a10-a327-f598b275d9a8.png)
- [ ] Results section 
![image](https://user-images.githubusercontent.com/89411909/134698117-4279a9d5-416a-44dc-b5be-0afd99d5d34f.png)
- [ ] Bottom Navigation Buttons 
![image](https://user-images.githubusercontent.com/89411909/134698177-dfe3a24e-8aeb-4ccc-9c66-60677f279d41.png)
- [ ] Powered by Dataverse (on all pages it appears)
![image](https://user-images.githubusercontent.com/89411909/134698235-52b4dfa3-e9ae-400e-b4c4-36feb89c1980.png)

### Advanced Search: 
- [ ] Find Button (at both the top and the bottom of the page): 
![image](https://user-images.githubusercontent.com/89411909/134710649-9c447bd1-849e-472c-8022-5237f03148cb.png)
- [ ] Each block of search filters (3) 
![image](https://user-images.githubusercontent.com/89411909/134710895-0bea7e4a-3ab5-4bf7-bfd6-938345f0b07e.png)
![image](https://user-images.githubusercontent.com/89411909/134710943-4536a2ac-bdf2-4605-9ddd-24cdf8b159f6.png)
![image](https://user-images.githubusercontent.com/89411909/134711184-8fe7af90-33b9-488b-bb1f-fda7a12493bd.png)

### (Sample Page): Data for: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent: https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F6YYA3O3
- [ ]  Data For: Qualitative....Header
- [ ] Citation
- [ ] Cite Data Project Button
- [ ] Learn About Citation Standards
- [ ] Download Data Project Blue Button
- [ ] Contact/Share Blue Button
- [ ] Make Data Count Metrics
- [ ] Description
- [ ] Files/Metadata/Terms/Version Header
- [ ] Search Label
![image](https://user-images.githubusercontent.com/89411909/135916419-759fe2a6-dec2-434f-bc36-0d1bd6915470.png)
- [ ] Search Data Project Textbox
- [ ] Filter by
- [ ] File Type Menu
- [ ] Access Menu
- [ ] File Tag Menu
- [ ] Group By Folder/Group by Tags boxes
- [ ] Blue Sort Button
- [ ] Data Table
![image](https://user-images.githubusercontent.com/89411909/135916831-a73f4bd2-906e-4440-a12a-63a23460d032.png)
- [ ] Metadata Tab: Export Metadata Button
- [ ] Metadata Tab: Metadata Table
![image](https://user-images.githubusercontent.com/89411909/135918139-e03ddddd-07dc-471a-a6a7-1a3add747357.png)
- [ ] Terms Tab: Waiver/Terms of Use Panel
- [ ] Terms Tab: Restricted Files, Terms of Access, Request Access Panel
- [ ] Terms Tab: Guestbook Panel
- [ ] Version Tab: Dataset Table

## (Sample Page) - Data For: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent - Data - VandeVusee-Mueller_CognitiveInternviewConsentForm.pdf: https://data.qdr.syr.edu/file.xhtml?persistentId=doi:10.5064/F6YYA3O3/ID8HVJ&version=1.0
- [ ] QDR Breadcrumb Trail
- [ ] Title of Data (VandeVusee....pdf)
- [ ] Cite file directly
- [ ] First Citation
- [ ] Cite Data File
- [ ] Each of the 3 options under Cite Data File (EndNote XML, RIS, BibTex)
- [ ] Learn about Data Citation Standards
- [ ] Cite the Data Project:
- [ ] Second Citation
- [ ] Cite Data Project
- [ ] Learn about Citation Standards
- [ ] All options under Download File Menu (File Access, Public, Download Options, Adobe PDF, Download Metadata, Data File Citation) 
- [ ] File Metrics
- [ ] Preview,Metadata,Versions
- [ ] Please confirm and/or complete..."
- [ ] Terms of Use
- [ ] Accept Button
- [ ] (After accepting terms): Read Document in New Window
- [ ] Under Metadata Tab: Export Metadata
- [ ] Under Metadata Tab: Metadata Information Panel
- [ ] Under Versions Tab: Versions Data Table

**Comment by qqmyers** [comment]
I think these warnings all go away with three changes - making the main part of the page have role="main", using role="banner" for the ~header (our Drupal header gets the navigation role), and making the Dataverse footer, which just has the 'powered by Dataverse' text as an <aside> (role = 'complementary') section (again our Drupal footer gets to be the real footer/contentinfo). Once those are in place, everything is in one of those landmarked areas. If we want finer-grained landmarks, or if the things I've mentioned don't sound appropriate, let me know.
