### ISSUE TITLE
Accessibility - Dataverse - ARIA Toggle Fields and Accessible Name

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#96]
### Data for: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent: https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F6YYA3O3

- [ ] Toggle Boxes for Data (all of them): 
![image](https://user-images.githubusercontent.com/89411909/134972919-65e24d62-7b3f-4499-8688-a872bb2fc44d.png)

**Comment by qqmyers** [comment]
Fixed
