### ISSUE TITLE
Accessibility - Dataverse - ARIA Role and Element

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#98]
### (Sample Page): Data for: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent: https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F6YYA3O3
- [ ] QDR Main Collection:
![image](https://user-images.githubusercontent.com/89411909/134978086-ffc1451e-5766-44a4-832e-8cc4e4ce67a0.png)

**Comment by qqmyers** [comment]
This applies to a header that we've disabled (display=none) in QDR (and Axe doesn't complain about this on demo.dataverse.org), so I'm just removing the hidden elements completely.
