### ISSUE TITLE
Accessibility - Dataverse - Links with Same Name

### ISSUE THREAD

**Issue by tander08** [QualitativeDataRepository/dataverse#99]
### (Sample Page): Data for: Qualitative Data Sharing: Participant Understanding, Motivation, and Consent: https://data.qdr.syr.edu/dataset.xhtml?persistentId=doi:10.5064/F6YYA3O3
- [x] The eye button next to each downloadable data/document (DevTools highlighted only the first one, my best guess is that the other buttons also have "Preview" as the accessible text, which is what DevTools is sensing; if not, that means there is another link on the page with "Preview" as the accessible text).

**Comment by qqmyers** [comment]
Change to have the span with "Preview" to say `Preview "<path>/<filename>" ` (and just `<filename>` if there is no path defined).
